### ISSUE TITLE
Logica para o campo Saldo em Associado

### ISSUE THREAD

**Issue by marisabarros11** [fflch/fac#15]
O campo precisa atualizar a cada compra ou pagamento feito pelo associado

**Comment by thiagogomesverissimo** [comment]
- Trocar o campo limite para double (8,2) - migration de alteração
- Arrumar os mutators para receber o campo como double- igual os model de venda
- Na página do associado mostrar o saldo: limite - soma da quantidade de parcelas em aberto*
- Na ato da compra, o valor total da comprar não pode ultrapassar o saldo

* saldo: limite - soma da quantidade de parcelas em aberto = colocar no model do associado

**Comment by ricardfo** [comment]
Implementado no commit  #2f9d7e1
