### ISSUE TITLE
Criar crud completo, seeder e fakers para Conveniado

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/fac#3]
![conveniado](https://user-images.githubusercontent.com/908508/93135910-73c29e00-f6b1-11ea-92b7-ca6e9233b888.png)

**Comment by thiagogomesverissimo** [comment]
Marisa, algum avanço?

**Comment by marisabarros11** [comment]
Oi Thiago, sim eu já fiz as migrations de todos os forms, assim como
seeders e fakers. Comecei as views, preciso só de mais um tempinho pra
organizar isso.
